### ISSUE TITLE
Script isn't working for me | The property 'properties' cannot be found on this object

### ISSUE THREAD

**Issue by emrecavalo** [stefanstranger/logicappdocs#42]
**Describe the bug**
Unfortunately it isn't possible to use the script. Every time when I try to run the script I got an error. First I had an other error regarding the property "location". I've defined the location manually in "New-LogicAppDoc.ps1" so the error is solved for now.

**Add error message**
New-LogicAppDoc.ps1: The property 'properties' cannot be found on this object. Verify that the property exists.
```PowerShell
Exception             :
    Type        : System.Management.Automation.PropertyNotFoundException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The property 'properties' cannot be found on this object. Verify that the property exists.
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : PropertyNotFoundStrict
        InvocationInfo        :
            ScriptLineNumber : 141
            OffsetInLine     : 38
            HistoryId        : 16
            ScriptName       : C:\Users\cavalo\logicappdocs\src\New-LogicAppDoc.ps1
            Line             : $Objects = Get-Action -Actions $($LogicApp.properties.definition.actions)

            Statement        : $LogicApp.properties.definition.actions
            PositionMessage  : At C:\Users\cavalo\logicappdocs\src\New-LogicAppDoc.ps1:141 char:38
                               + … ects = Get-Action -Actions $($LogicApp.properties.definition.actions)
                               +                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : C:\Users\cavalo\logicappdocs\src
            PSCommandPath    : C:\Users\cavalo\logicappdocs\src\New-LogicAppDoc.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, C:\Users\cavalo\logicappdocs\src\New-LogicAppDoc.ps1: line 141
                                at <ScriptBlock>, <No file>: line 1
    TargetSite  :
        Name          : CheckActionPreference
        DeclaringType : System.Management.Automation.ExceptionHandlingOps, System.Management.Automation,
Version=7.4.1.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The property 'properties' cannot be found on this object. Verify that the property exists.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception
exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object
inputToProcess)
   at System.Management.Automation.CommandProcessorBase.Complete()
CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
FullyQualifiedErrorId : PropertyNotFoundStrict
InvocationInfo        :
    ScriptLineNumber : 141
    OffsetInLine     : 38
    HistoryId        : 16
    ScriptName       : C:\Users\cavalo\logicappdocs\src\New-LogicAppDoc.ps1
    Line             : $Objects = Get-Action -Actions $($LogicApp.properties.definition.actions)

    Statement        : $LogicApp.properties.definition.actions
    PositionMessage  : At C:\Users\cavalo\logicappdocs\src\New-LogicAppDoc.ps1:141 char:38
                       + … ects = Get-Action -Actions $($LogicApp.properties.definition.actions)
                       +                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\Users\cavalo\logicappdocs\src
    PSCommandPath    : C:\Users\cavalo\logicappdocs\src\New-LogicAppDoc.ps1
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, C:\Users\cavalo\logicappdocs\src\New-LogicAppDoc.ps1: line 141
                        at <ScriptBlock>, <No file>: line 1
```

**To Reproduce**

If possible upload the Logic App Flow or Power Automate Flow code.

**Expected behavior**

**Screenshots**

**PowerShell version:**
Run $PSVersionTable command in PowerShell host
e.g.
```PowerShelll
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
**LogicAppDocs version**
 - Version [e.g. 1.1.5]

**Additional context**

**Comment by gooseleggs** [comment]
This is a continuation of the location issue that you are having. What diss the $LogicApp variable contain?  Everything is driven from this variable.  I suspect that it is not getting what we need and it is not erroring out. 

Is this a consumption logic app?
Workaround to go into the logic app and create a file from the code view and use that as input.
